using Godot;
using System;

public partial class blob_spire : RigidBody3D
{
	private Random random = new Random();
	private AnimatedSprite3D animatedSprite;
	private CollisionShape3D collisionShape;

	public float health = 100;
	public float spawnOffset = 1f;

	private bool isProducing = false;
	private float timer = 0f;
	private float cooldownTime = .1f; 

	// Add the goops scenes to be generated by the well
	private PackedScene blobScene = GD.Load<PackedScene>("res://scenes/enemies/prickle_blob.tscn");

	public override void _Ready()
	{
		animatedSprite = GetNode<AnimatedSprite3D>("blob_spire_anim");
		collisionShape = GetNode<CollisionShape3D>("blob_spire_collide");
		animatedSprite.Play("idle");
	}

	public override void _PhysicsProcess(double delta)
	{
		// Do nothing if its currently making a goop
		if (isProducing) return;
		// Othewise idle
		animatedSprite.Play("idle");
		timer -= (float)delta;
		if (timer <= 0)
		{
			int produceChance = random.Next(0, 10); 
			if (produceChance < 9) 
			{
				// Loads the sequence to produce a blob: playing the anim/spawning
				_ = StartProduction();
			}
			timer = cooldownTime;
		}
	}

	private async System.Threading.Tasks.Task StartProduction()
	{
		isProducing = true;
		animatedSprite.Play("produce");
		//IF THIS DOESNT WORK CHECK THE ANIMATION LOOP!!!!!!!!! CANT LOOP IN PRODUCE
		await ToSignal(animatedSprite, "animation_finished");
		SpawnBlob();
		isProducing = false;
	}

	private void SpawnBlob()
	{
		Node3D blob = (Node3D)blobScene.Instantiate();
		Vector3 spawnPosition = GlobalTransform.Origin + GlobalTransform.Basis.Z * spawnOffset * 1.5f;
		GetParent().AddChild(blob); 
	}
}
