using Godot;
using System;

public partial class BubbleHut : RigidBody3D
{
	// Building for Home. Increases goop from 5 to 10 if loaded in home node.
	private Random random = new Random();
	private AnimatedSprite3D animatedSprite;
	private CollisionShape3D collisionShape;

	public float health = 100;
	public float spawnOffset = 1f;

	private bool isProducing = false;
	private float timer = 0f;
	private float cooldownTime = .1f; 

	// Add the goops scenes to be generated by the well
	private PackedScene blobScene = GD.Load<PackedScene>("res://scenes/enemies/prickle_blob.tscn");

	public override void _Ready()
	{
		animatedSprite = GetNode<AnimatedSprite3D>("blob_spire_anim");
		collisionShape = GetNode<CollisionShape3D>("blob_spire_collide");
		animatedSprite.Play("idle");
	}

	public override void _PhysicsProcess(double delta)
	{
		
	}
}
